<?php

/**
 * @var \Vindi\VP\Block\Custom\PaymentLinkSuccess $block
 */

$order = $block->getOrder();
$payment = $order->getPayment();
$paymentMethod = $payment->getMethod();
$paymentTitle = $payment->getMethodInstance()->getTitle();
$message = $paymentMethod == 'vindi_vp_cc' ? 'Thank you! Your order has been successfully placed and is being processed.' : 'Thank you! Your order has been successfully placed and will be processed after payment.'
?>
<div class="payment-success">
    <div class="payment-success__header">
        <svg class="payment-success__ico" width="47" height="47" viewBox="0 0 47 47" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M47 23.5C47 36.4786 36.4786 47 23.5 47C10.5213 47 0 36.4786 0 23.5C0 10.5213 10.5213 0 23.5 0C36.4786 0 47 10.5213 47 23.5ZM32.9712 16.3787C33.6595 17.067 33.6595 18.183 32.9712 18.8712L21.2212 30.6212C20.5329 31.3095 19.4171 31.3095 18.7287 30.6212L14.0287 25.9212C13.3404 25.2329 13.3404 24.1171 14.0287 23.4288C14.717 22.7405 15.833 22.7405 16.5213 23.4288L19.975 26.8824L25.2268 21.6306L30.4788 16.3787C31.1671 15.6904 32.2829 15.6904 32.9712 16.3787Z" fill="#7CC245"/>
        </svg>
        <h2 class="payment-success__title"><?= __($message); ?></h2>
        <span class="payment-success__subtitle"><?= __($this->getInstructions()) ?></span>
    </div>
    <?php if ($paymentMethod == 'vindi_vp_cc'): ?>
        <div class="vindi-vp-cc container button-container">
            <form action="<?= $block->getBaseUrl() . 'sales/order/history' ?>" method="GET">
                <button class="pix-copy-button action primary" type="submit">
                    <?= __('My Orders') ?>
                </button>
            </form>
        </div>
    <?php endif;?>
    
    <?php if ($paymentMethod == 'vindi_vp_pix'): ?>
    <?php
        $qrCodeImage = (string) $payment->getAdditionalInformation('qr_code_url');
        $emv = (string) $payment->getAdditionalInformation('qr_code_emv');
    ?>
        <?php if ($qrCodeImage): ?>
        <div class="vindi-pix pix payment-success__container">
            <div class="content">
                <div class="qrcode">
                    <h3><?= __('Pay with Pix:') ?></h3>
                    <img alt="<?= __('QRCode') ?>" src="<?= $qrCodeImage ?>" class="vindi-pix-qrcode" />
                </div>
                <div class="pix-code">
                    <strong><?= __('Pix code:') ?></strong>
                    <div class="pix-qrcode"><?= $emv ?></div>
                    <div class="align-button">
                        <button class="pix-copy-button"
                                data-text="<?= $block->escapeHtml(__('Copied!')) ?>"
                                onclick="vindiVp.copyCode(this, '.pix-qrcode', false)">
                            <?= __('Copy PIX code') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
    <?php endif;?>
    
    <?php if ($paymentMethod == 'vindi_vp_bankslippix'): ?>
        <?php
        $qrCodeImage = (string) $payment->getAdditionalInformation('qr_code_url');
        $emv = (string) $payment->getAdditionalInformation('qr_code_emv');
        $bankSlipUrl = (string) $payment->getAdditionalInformation('bank_slip_url');
        $bankSlipNumber = (string) $payment->getAdditionalInformation('bank_slip_number');
        ?>
                <div class="button-container">
                    <?php if ($bankSlipUrl): ?>
                        <form action="<?= $bankSlipUrl?>" method="GET" target="_blank" >
                            <button class="pix-copy-button action primary" type="submit">
                                <?= __('View BankslipPix') ?>
                            </button>
                        </form>
                    <?php endif; ?>
                </div>
                <div class="vindi-bankslippix container payment-success__container">
                    <div class="vindi-bankslip bankslip">
                        <h3><?= __('Pay with Bankslip:') ?></h3>
                        <div class="bankslip-barcode-container">
                            <div class="bankslip-img-code">
                                <div class="bankslip-number-container">
                                    <strong><?= __('Bankslip code:') ?></strong>
                                    <div class="bankslip-number"><?= $bankSlipNumber ?></div>
                                </div>
                                <button class="bankslip-copy-button"
                                        data-text="<?= $block->escapeHtml(__('Copied!')) ?>"
                                        onclick="vindiVp.copyCode(this, '.bankslip-number', false)">
                                    <?= __('Copy Barcode') ?>
                                </button>
                            </div>
                        </div>
                    </div>
                    <?php if ($qrCodeImage): ?>
                        <div class="vindi-pix pix">
                            <h3><?= __('Pay with Pix:') ?></h3>
                            <div class="pix-barcode-container">
                                <div class="pix-img-code">
                                    <?php if ($qrCodeImage): ?>
                                        <img alt="<?= __('QRCode') ?>" src="<?= $qrCodeImage ?>" class="vindi-pix-qrcode" />
                                    <?php endif; ?>
                                    <strong><?= __('Pix code:') ?></strong>
                                    <div class="pix-qrcode"><?= $emv ?></div>
                                    <button class="pix-copy-button"
                                            data-text="<?= $block->escapeHtml(__('Copied!')) ?>"
                                            onclick="vindiVp.copyCode(this, '.pix-qrcode', false)">
                                        <?= __('Copy PIX code') ?>
                                    </button>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
    <?php endif;?>
    
    <?php if ($paymentMethod == 'vindi_vp_bankslip'): ?>
        <?php
            $bankSlipUrl = (string) $payment->getAdditionalInformation('bank_slip_url');
            $bankSlipNumber = (string) $payment->getAdditionalInformation('bank_slip_number');
        ?>
        <div class="button-container">
            <?php if ($bankSlipUrl): ?>
                <form action="<?= $bankSlipUrl?>" method="GET" target="_blank" >
                    <button class="pix-copy-button action primary" type="submit">
                        <?= __('View Bankslip') ?>
                    </button>
                </form>
            <?php endif; ?>
        </div>
        <div class="vindi-vp-bankslip payment-success__container">
            <div class="content">
                <h3><?= __('Pay with Bankslip:') ?></h3>
                <div class="vindi-bankslip bankslip">
                    <div class="bankslip-barcode-container">
                        <div class="bankslip-number-container">
                            <strong><?= __('Bankslip code:') ?></strong>
                            <div class="bankslip-number"><?= $bankSlipNumber ?></div>
                        </div>
                    </div>
                </div>
                <div class="align-button">
                    <button class="bankslip-copy-button"
                            data-text="<?= $block->escapeHtml(__('Copied!')) ?>"
                            onclick="vindiVp.copyCode(this, '.bankslip-number', false)">
                        <?= __('Copy Barcode') ?>
                    </button>
                </div>
            </div>
        </div>
    <?php endif;?>
</div>
