<?php

/**
 * @var Vindi\VP\Block\Adminhtml\Order\LinkField $block
 * @var \Magento\Framework\Escaper $escaper
 */
$paymentLink = $block->getPaymentLink();
?>
<?php if(str_contains($block->getPaymentMethod(), $block::VINDI_PAYMENT_LINK)): ?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title">
              <?php /* @escapeNotVerified */ echo __('Payment Link') ?>
        </span>
    </div>
    <div class="admin__page-section-item-content edit-checkoutfield-date"
         style="display: flex;flex-direction: row;flex-wrap: nowrap;align-items: center;"
         id="edit-checkoutfield-info-form">
        <fieldset class="admin__fieldset" style="display: <?= !$paymentLink ? 'none' : 'block' ?>">
            <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
            <input type="hidden" id="orderid" value="<?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $buttonLabel = $paymentLink ? __('Send Payment Link') : __('Create and Send New Payment Link');
            $request = $objectManager->get('Magento\Framework\App\Request\Http');
            echo $param = $request->getParam('order_id');?>"/>
            <span class="link" style="display: none"><?= $paymentLink; ?></span>
            <input type="text"
                   class="admin__control-text"
                   value="<?php echo $paymentLink; ?>"
                   style="margin-right: 10px"
                   readonly>
            <button class="pix-copy-button"
                    style="margin-right: 10px"
                    data-text="<?= $block->escapeHtml(__('Copied!')) ?>"
                    onclick="vindiVp.copyCode(this, '.link', false)">
                <?= $block->escapeHtml(__('Copy link')) ?>
            </button>
        </fieldset>
        <button id="send" class="action-default action-secondary action-send"><?php /* @escapeNotVerified */ echo $buttonLabel ?></button>
    </div>
</section>

<script type="text/javascript">
    require([
        'jquery',
        'loader',
        'domReady!',
        'mage/validation',
        'mage/translate',
        'jquery/ui'
    ], function ($) {
        $("#send").click(function() {
            $('#loader-example').trigger('processStart');

            var orderId = $('#orderid').val();
            var formKey = $('input[name="form_key"]').val();
            var url = '<?= /** @noEscape */ $block->getUrl("vindi_vp/paymentlink/send")?>';

            $(document.body).trigger('processStart');

            $.ajax({
                url: url,
                data: {
                    order_id: orderId,
                    form_key: formKey
                },
                type: "POST",
            }).always(function () {
                $(document.body).trigger('processStop');
                location.reload();
            });

        });
    });
</script>
<?php endif?>
